### PR TITLE
git big approach

### PR DESCRIPTION
**Pull request by SotoArmando**
I will appreciate the review n.n.

### CODE REVIEW

**Comment by dipto0321** [comment]
Hi @Macatuz ,

Nice work 👏 . But need to work a little bit more.

- No need to include Enumerable inside Array and Hash class.
- my_each works perfectly for an array. but not works perfectly for a hash. Check these pictures.




- my_each_with_index work properly for an array but not for a hash. check out the image


- my_select also work for an array. Not for a hash.



- my_all does not work for both Array and Hash.

- my_any not working for an array.

- my_none not working
- my_count should also work with argument and block like the original one.
- my_map not working.

- Where is the #multply_els method? [Point number 10](https://prnt.sc/nn8bnq)

**_P.S: If you want to skip `Hash` or `Range` feature for your Enumerable methods. You can. But I will recommend you to try this thing also._** 

After fixing all this problem test your all method with original method output. If it's same then please send another request to review this project. Let me know if you have any question.

Thanks 🙏

**Comment by SotoArmando** [comment]
I see. I will look forward for those issues, sorry for not notice that before got being quick out of hand that was my mistake.

**Comment by dipto0321** [comment]
Hi @Macatuz ,

Still this project has lot's of thing which should be fixed. Check out points below: 

> No need to include Enumerable inside Array and Hash class.

What I mean to say remove this code

```
class Array
  include Enumerable
end


class Hash
  include Enumerable
end
```
Because when you do something inside this 
```
module Enumerable

end
```
Means you adding your own methods with builtin one. So that you don't need to include this module inside `Array` and `Hash` class.

> my_count should also work with argument and block like the original one.

Means I can call `[1,2,3].my_count(3)` which will return `1`. Also, `[1,2,3].my_count { | x| x>1 }` will return `2`.

Please, fix this and send another code request to re-review this project. Don't hesitate to ask me any question about this feedback 😃 . Just mention me with your reply.

p.s: If you understood properly built-in `Enumerable`  methods then you shouldn't have any problem with your method. So if needed then I will recommend you to take some time and review those topics again. 🙂 

Thanks 🙏

**Comment by SotoArmando** [comment]
@dipto0321  there is a thing i wasnt able to figure out, as when i call count(arg) over and array it just returns me count over number of arg === elements. 

[1,2,3].my_count(3) which will return 3(arg)+3(arr.length) = 6
I tested calling [1, 2, 3,].count(3) and it returns 1. exactly what I am missing?

**Comment by dipto0321** [comment]
Hi @Macatuz ,

Sorry I was wrong ... Actually what happens there when you pass an argument like `3` what it actually return the number of `3` in passing example array. According to the above example. `[1,2,3].my_count(3)` will return `1` because in that array there is one `3` element. If the array is like that `[1,2,2,2,3]` and I call `my_count(2)` then it will return `3`. Because there are 3 `2` in the array.

I hope this will help you. Sorry for my wrong info. and thanks for sharing it with me 🎖 

Thanks 🙏

**Comment by dipto0321** [comment]
Hi @Macatuz ,

All is well. This is from me 👍 . You can merge it into the master now. 

Thanks 💯 ☺️

**Comment by SotoArmando** [comment]
@dipto0321  thanks for the review ^^

**Comment by dipto0321** [comment]
> @dipto0321 thanks for the review ^^

@Macatuz You welcome 🤗

**Pull request merged**
